### ISSUE TITLE
Add ability to specify comma separated extensions in config.yaml

### ISSUE THREAD

**Issue by judahpaul16** [judahpaul16/dirconfig#3]
Currently extensions are specified one per line in the config.yaml like so:
```yaml
rules: 
  - extension: .jpg
    destination: /images
  - extension: .png
    destination: /images
```

Allow for specifying comma separated extensions like so:

```yaml
rules: 
  - extension: .jpg, .jpeg, .png
    destination: /images
```
